#pragma once

#include "IconsFontAwesome6.h"

namespace InfoWidgets::IconCatalog
{
    struct Entry
    {
        const char *name;
        const char *glyph;
    };

    inline constexpr Entry kEntries[] = {
        {"0", ICON_FA_0},
        {"1", ICON_FA_1},
        {"2", ICON_FA_2},
        {"3", ICON_FA_3},
        {"4", ICON_FA_4},
        {"5", ICON_FA_5},
        {"6", ICON_FA_6},
        {"7", ICON_FA_7},
        {"8", ICON_FA_8},
        {"9", ICON_FA_9},
        {"A", ICON_FA_A},
        {"Address Book", ICON_FA_ADDRESS_BOOK},
        {"Address Card", ICON_FA_ADDRESS_CARD},
        {"Align Center", ICON_FA_ALIGN_CENTER},
        {"Align Justify", ICON_FA_ALIGN_JUSTIFY},
        {"Align Left", ICON_FA_ALIGN_LEFT},
        {"Align Right", ICON_FA_ALIGN_RIGHT},
        {"Anchor", ICON_FA_ANCHOR},
        {"Anchor Circle Check", ICON_FA_ANCHOR_CIRCLE_CHECK},
        {"Anchor Circle Exclamation", ICON_FA_ANCHOR_CIRCLE_EXCLAMATION},
        {"Anchor Circle Xmark", ICON_FA_ANCHOR_CIRCLE_XMARK},
        {"Anchor Lock", ICON_FA_ANCHOR_LOCK},
        {"Angle Down", ICON_FA_ANGLE_DOWN},
        {"Angle Left", ICON_FA_ANGLE_LEFT},
        {"Angle Right", ICON_FA_ANGLE_RIGHT},
        {"Angle Up", ICON_FA_ANGLE_UP},
        {"Angles Down", ICON_FA_ANGLES_DOWN},
        {"Angles Left", ICON_FA_ANGLES_LEFT},
        {"Angles Right", ICON_FA_ANGLES_RIGHT},
        {"Angles Up", ICON_FA_ANGLES_UP},
        {"Ankh", ICON_FA_ANKH},
        {"Apple Whole", ICON_FA_APPLE_WHOLE},
        {"Archway", ICON_FA_ARCHWAY},
        {"Arrow Down", ICON_FA_ARROW_DOWN},
        {"Arrow Down 1 9", ICON_FA_ARROW_DOWN_1_9},
        {"Arrow Down 9 1", ICON_FA_ARROW_DOWN_9_1},
        {"Arrow Down A Z", ICON_FA_ARROW_DOWN_A_Z},
        {"Arrow Down Long", ICON_FA_ARROW_DOWN_LONG},
        {"Arrow Down Short Wide", ICON_FA_ARROW_DOWN_SHORT_WIDE},
        {"Arrow Down Up Across Line", ICON_FA_ARROW_DOWN_UP_ACROSS_LINE},
        {"Arrow Down Up Lock", ICON_FA_ARROW_DOWN_UP_LOCK},
        {"Arrow Down Wide Short", ICON_FA_ARROW_DOWN_WIDE_SHORT},
        {"Arrow Down Z A", ICON_FA_ARROW_DOWN_Z_A},
        {"Arrow Left", ICON_FA_ARROW_LEFT},
        {"Arrow Left Long", ICON_FA_ARROW_LEFT_LONG},
        {"Arrow Pointer", ICON_FA_ARROW_POINTER},
        {"Arrow Right", ICON_FA_ARROW_RIGHT},
        {"Arrow Right Arrow Left", ICON_FA_ARROW_RIGHT_ARROW_LEFT},
        {"Arrow Right From Bracket", ICON_FA_ARROW_RIGHT_FROM_BRACKET},
        {"Arrow Right Long", ICON_FA_ARROW_RIGHT_LONG},
        {"Arrow Right To Bracket", ICON_FA_ARROW_RIGHT_TO_BRACKET},
        {"Arrow Right To City", ICON_FA_ARROW_RIGHT_TO_CITY},
        {"Arrow Rotate Left", ICON_FA_ARROW_ROTATE_LEFT},
        {"Arrow Rotate Right", ICON_FA_ARROW_ROTATE_RIGHT},
        {"Arrow Trend Down", ICON_FA_ARROW_TREND_DOWN},
        {"Arrow Trend Up", ICON_FA_ARROW_TREND_UP},
        {"Arrow Turn Down", ICON_FA_ARROW_TURN_DOWN},
        {"Arrow Turn Up", ICON_FA_ARROW_TURN_UP},
        {"Arrow Up", ICON_FA_ARROW_UP},
        {"Arrow Up 1 9", ICON_FA_ARROW_UP_1_9},
        {"Arrow Up 9 1", ICON_FA_ARROW_UP_9_1},
        {"Arrow Up A Z", ICON_FA_ARROW_UP_A_Z},
        {"Arrow Up From Bracket", ICON_FA_ARROW_UP_FROM_BRACKET},
        {"Arrow Up From Ground Water", ICON_FA_ARROW_UP_FROM_GROUND_WATER},
        {"Arrow Up From Water Pump", ICON_FA_ARROW_UP_FROM_WATER_PUMP},
        {"Arrow Up Long", ICON_FA_ARROW_UP_LONG},
        {"Arrow Up Right Dots", ICON_FA_ARROW_UP_RIGHT_DOTS},
        {"Arrow Up Right From Square", ICON_FA_ARROW_UP_RIGHT_FROM_SQUARE},
        {"Arrow Up Short Wide", ICON_FA_ARROW_UP_SHORT_WIDE},
        {"Arrow Up Wide Short", ICON_FA_ARROW_UP_WIDE_SHORT},
        {"Arrow Up Z A", ICON_FA_ARROW_UP_Z_A},
        {"Arrows Down To Line", ICON_FA_ARROWS_DOWN_TO_LINE},
        {"Arrows Down To People", ICON_FA_ARROWS_DOWN_TO_PEOPLE},
        {"Arrows Left Right", ICON_FA_ARROWS_LEFT_RIGHT},
        {"Arrows Left Right To Line", ICON_FA_ARROWS_LEFT_RIGHT_TO_LINE},
        {"Arrows Rotate", ICON_FA_ARROWS_ROTATE},
        {"Arrows Spin", ICON_FA_ARROWS_SPIN},
        {"Arrows Split Up And Left", ICON_FA_ARROWS_SPLIT_UP_AND_LEFT},
        {"Arrows To Circle", ICON_FA_ARROWS_TO_CIRCLE},
        {"Arrows To Dot", ICON_FA_ARROWS_TO_DOT},
        {"Arrows To Eye", ICON_FA_ARROWS_TO_EYE},
        {"Arrows Turn Right", ICON_FA_ARROWS_TURN_RIGHT},
        {"Arrows Turn To Dots", ICON_FA_ARROWS_TURN_TO_DOTS},
        {"Arrows Up Down", ICON_FA_ARROWS_UP_DOWN},
        {"Arrows Up Down Left Right", ICON_FA_ARROWS_UP_DOWN_LEFT_RIGHT},
        {"Arrows Up To Line", ICON_FA_ARROWS_UP_TO_LINE},
        {"Asterisk", ICON_FA_ASTERISK},
        {"At", ICON_FA_AT},
        {"Atom", ICON_FA_ATOM},
        {"Audio Description", ICON_FA_AUDIO_DESCRIPTION},
        {"Austral Sign", ICON_FA_AUSTRAL_SIGN},
        {"Award", ICON_FA_AWARD},
        {"B", ICON_FA_B},
        {"Baby", ICON_FA_BABY},
        {"Baby Carriage", ICON_FA_BABY_CARRIAGE},
        {"Backward", ICON_FA_BACKWARD},
        {"Backward Fast", ICON_FA_BACKWARD_FAST},
        {"Backward Step", ICON_FA_BACKWARD_STEP},
        {"Bacon", ICON_FA_BACON},
        {"Bacteria", ICON_FA_BACTERIA},
        {"Bacterium", ICON_FA_BACTERIUM},
        {"Bag Shopping", ICON_FA_BAG_SHOPPING},
        {"Bahai", ICON_FA_BAHAI},
        {"Baht Sign", ICON_FA_BAHT_SIGN},
        {"Ban", ICON_FA_BAN},
        {"Ban Smoking", ICON_FA_BAN_SMOKING},
        {"Bandage", ICON_FA_BANDAGE},
        {"Bangladeshi Taka Sign", ICON_FA_BANGLADESHI_TAKA_SIGN},
        {"Barcode", ICON_FA_BARCODE},
        {"Bars", ICON_FA_BARS},
        {"Bars Progress", ICON_FA_BARS_PROGRESS},
        {"Bars Staggered", ICON_FA_BARS_STAGGERED},
        {"Baseball", ICON_FA_BASEBALL},
        {"Baseball Bat Ball", ICON_FA_BASEBALL_BAT_BALL},
        {"Basket Shopping", ICON_FA_BASKET_SHOPPING},
        {"Basketball", ICON_FA_BASKETBALL},
        {"Bath", ICON_FA_BATH},
        {"Battery Empty", ICON_FA_BATTERY_EMPTY},
        {"Battery Full", ICON_FA_BATTERY_FULL},
        {"Battery Half", ICON_FA_BATTERY_HALF},
        {"Battery Quarter", ICON_FA_BATTERY_QUARTER},
        {"Battery Three Quarters", ICON_FA_BATTERY_THREE_QUARTERS},
        {"Bed", ICON_FA_BED},
        {"Bed Pulse", ICON_FA_BED_PULSE},
        {"Beer Mug Empty", ICON_FA_BEER_MUG_EMPTY},
        {"Bell", ICON_FA_BELL},
        {"Bell Concierge", ICON_FA_BELL_CONCIERGE},
        {"Bell Slash", ICON_FA_BELL_SLASH},
        {"Bezier Curve", ICON_FA_BEZIER_CURVE},
        {"Bicycle", ICON_FA_BICYCLE},
        {"Binoculars", ICON_FA_BINOCULARS},
        {"Biohazard", ICON_FA_BIOHAZARD},
        {"Bitcoin Sign", ICON_FA_BITCOIN_SIGN},
        {"Blender", ICON_FA_BLENDER},
        {"Blender Phone", ICON_FA_BLENDER_PHONE},
        {"Blog", ICON_FA_BLOG},
        {"Bold", ICON_FA_BOLD},
        {"Bolt", ICON_FA_BOLT},
        {"Bolt Lightning", ICON_FA_BOLT_LIGHTNING},
        {"Bomb", ICON_FA_BOMB},
        {"Bone", ICON_FA_BONE},
        {"Bong", ICON_FA_BONG},
        {"Book", ICON_FA_BOOK},
        {"Book Atlas", ICON_FA_BOOK_ATLAS},
        {"Book Bible", ICON_FA_BOOK_BIBLE},
        {"Book Bookmark", ICON_FA_BOOK_BOOKMARK},
        {"Book Journal Whills", ICON_FA_BOOK_JOURNAL_WHILLS},
        {"Book Medical", ICON_FA_BOOK_MEDICAL},
        {"Book Open", ICON_FA_BOOK_OPEN},
        {"Book Open Reader", ICON_FA_BOOK_OPEN_READER},
        {"Book Quran", ICON_FA_BOOK_QURAN},
        {"Book Skull", ICON_FA_BOOK_SKULL},
        {"Book Tanakh", ICON_FA_BOOK_TANAKH},
        {"Bookmark", ICON_FA_BOOKMARK},
        {"Border All", ICON_FA_BORDER_ALL},
        {"Border None", ICON_FA_BORDER_NONE},
        {"Border Top Left", ICON_FA_BORDER_TOP_LEFT},
        {"Bore Hole", ICON_FA_BORE_HOLE},
        {"Bottle Droplet", ICON_FA_BOTTLE_DROPLET},
        {"Bottle Water", ICON_FA_BOTTLE_WATER},
        {"Bowl Food", ICON_FA_BOWL_FOOD},
        {"Bowl Rice", ICON_FA_BOWL_RICE},
        {"Bowling Ball", ICON_FA_BOWLING_BALL},
        {"Box", ICON_FA_BOX},
        {"Box Archive", ICON_FA_BOX_ARCHIVE},
        {"Box Open", ICON_FA_BOX_OPEN},
        {"Box Tissue", ICON_FA_BOX_TISSUE},
        {"Boxes Packing", ICON_FA_BOXES_PACKING},
        {"Boxes Stacked", ICON_FA_BOXES_STACKED},
        {"Braille", ICON_FA_BRAILLE},
        {"Brain", ICON_FA_BRAIN},
        {"Brazilian Real Sign", ICON_FA_BRAZILIAN_REAL_SIGN},
        {"Bread Slice", ICON_FA_BREAD_SLICE},
        {"Bridge", ICON_FA_BRIDGE},
        {"Bridge Circle Check", ICON_FA_BRIDGE_CIRCLE_CHECK},
        {"Bridge Circle Exclamation", ICON_FA_BRIDGE_CIRCLE_EXCLAMATION},
        {"Bridge Circle Xmark", ICON_FA_BRIDGE_CIRCLE_XMARK},
        {"Bridge Lock", ICON_FA_BRIDGE_LOCK},
        {"Bridge Water", ICON_FA_BRIDGE_WATER},
        {"Briefcase", ICON_FA_BRIEFCASE},
        {"Briefcase Medical", ICON_FA_BRIEFCASE_MEDICAL},
        {"Broom", ICON_FA_BROOM},
        {"Broom Ball", ICON_FA_BROOM_BALL},
        {"Brush", ICON_FA_BRUSH},
        {"Bucket", ICON_FA_BUCKET},
        {"Bug", ICON_FA_BUG},
        {"Bug Slash", ICON_FA_BUG_SLASH},
        {"Bugs", ICON_FA_BUGS},
        {"Building", ICON_FA_BUILDING},
        {"Building Circle Arrow Right", ICON_FA_BUILDING_CIRCLE_ARROW_RIGHT},
        {"Building Circle Check", ICON_FA_BUILDING_CIRCLE_CHECK},
        {"Building Circle Exclamation", ICON_FA_BUILDING_CIRCLE_EXCLAMATION},
        {"Building Circle Xmark", ICON_FA_BUILDING_CIRCLE_XMARK},
        {"Building Columns", ICON_FA_BUILDING_COLUMNS},
        {"Building Flag", ICON_FA_BUILDING_FLAG},
        {"Building Lock", ICON_FA_BUILDING_LOCK},
        {"Building Ngo", ICON_FA_BUILDING_NGO},
        {"Building Shield", ICON_FA_BUILDING_SHIELD},
        {"Building Un", ICON_FA_BUILDING_UN},
        {"Building User", ICON_FA_BUILDING_USER},
        {"Building Wheat", ICON_FA_BUILDING_WHEAT},
        {"Bullhorn", ICON_FA_BULLHORN},
        {"Bullseye", ICON_FA_BULLSEYE},
        {"Burger", ICON_FA_BURGER},
        {"Burst", ICON_FA_BURST},
        {"Bus", ICON_FA_BUS},
        {"Bus Simple", ICON_FA_BUS_SIMPLE},
        {"Business Time", ICON_FA_BUSINESS_TIME},
        {"C", ICON_FA_C},
        {"Cable Car", ICON_FA_CABLE_CAR},
        {"Cake Candles", ICON_FA_CAKE_CANDLES},
        {"Calculator", ICON_FA_CALCULATOR},
        {"Calendar", ICON_FA_CALENDAR},
        {"Calendar Check", ICON_FA_CALENDAR_CHECK},
        {"Calendar Day", ICON_FA_CALENDAR_DAY},
        {"Calendar Days", ICON_FA_CALENDAR_DAYS},
        {"Calendar Minus", ICON_FA_CALENDAR_MINUS},
        {"Calendar Plus", ICON_FA_CALENDAR_PLUS},
        {"Calendar Week", ICON_FA_CALENDAR_WEEK},
        {"Calendar Xmark", ICON_FA_CALENDAR_XMARK},
        {"Camera", ICON_FA_CAMERA},
        {"Camera Retro", ICON_FA_CAMERA_RETRO},
        {"Camera Rotate", ICON_FA_CAMERA_ROTATE},
        {"Campground", ICON_FA_CAMPGROUND},
        {"Candy Cane", ICON_FA_CANDY_CANE},
        {"Cannabis", ICON_FA_CANNABIS},
        {"Capsules", ICON_FA_CAPSULES},
        {"Car", ICON_FA_CAR},
        {"Car Battery", ICON_FA_CAR_BATTERY},
        {"Car Burst", ICON_FA_CAR_BURST},
        {"Car On", ICON_FA_CAR_ON},
        {"Car Rear", ICON_FA_CAR_REAR},
        {"Car Side", ICON_FA_CAR_SIDE},
        {"Car Tunnel", ICON_FA_CAR_TUNNEL},
        {"Caravan", ICON_FA_CARAVAN},
        {"Caret Down", ICON_FA_CARET_DOWN},
        {"Caret Left", ICON_FA_CARET_LEFT},
        {"Caret Right", ICON_FA_CARET_RIGHT},
        {"Caret Up", ICON_FA_CARET_UP},
        {"Carrot", ICON_FA_CARROT},
        {"Cart Arrow Down", ICON_FA_CART_ARROW_DOWN},
        {"Cart Flatbed", ICON_FA_CART_FLATBED},
        {"Cart Flatbed Suitcase", ICON_FA_CART_FLATBED_SUITCASE},
        {"Cart Plus", ICON_FA_CART_PLUS},
        {"Cart Shopping", ICON_FA_CART_SHOPPING},
        {"Cash Register", ICON_FA_CASH_REGISTER},
        {"Cat", ICON_FA_CAT},
        {"Cedi Sign", ICON_FA_CEDI_SIGN},
        {"Cent Sign", ICON_FA_CENT_SIGN},
        {"Certificate", ICON_FA_CERTIFICATE},
        {"Chair", ICON_FA_CHAIR},
        {"Chalkboard", ICON_FA_CHALKBOARD},
        {"Chalkboard User", ICON_FA_CHALKBOARD_USER},
        {"Champagne Glasses", ICON_FA_CHAMPAGNE_GLASSES},
        {"Charging Station", ICON_FA_CHARGING_STATION},
        {"Chart Area", ICON_FA_CHART_AREA},
        {"Chart Bar", ICON_FA_CHART_BAR},
        {"Chart Column", ICON_FA_CHART_COLUMN},
        {"Chart Diagram", ICON_FA_CHART_DIAGRAM},
        {"Chart Gantt", ICON_FA_CHART_GANTT},
        {"Chart Line", ICON_FA_CHART_LINE},
        {"Chart Pie", ICON_FA_CHART_PIE},
        {"Chart Simple", ICON_FA_CHART_SIMPLE},
        {"Check", ICON_FA_CHECK},
        {"Check Double", ICON_FA_CHECK_DOUBLE},
        {"Check To Slot", ICON_FA_CHECK_TO_SLOT},
        {"Cheese", ICON_FA_CHEESE},
        {"Chess", ICON_FA_CHESS},
        {"Chess Bishop", ICON_FA_CHESS_BISHOP},
        {"Chess Board", ICON_FA_CHESS_BOARD},
        {"Chess King", ICON_FA_CHESS_KING},
        {"Chess Knight", ICON_FA_CHESS_KNIGHT},
        {"Chess Pawn", ICON_FA_CHESS_PAWN},
        {"Chess Queen", ICON_FA_CHESS_QUEEN},
        {"Chess Rook", ICON_FA_CHESS_ROOK},
        {"Chevron Down", ICON_FA_CHEVRON_DOWN},
        {"Chevron Left", ICON_FA_CHEVRON_LEFT},
        {"Chevron Right", ICON_FA_CHEVRON_RIGHT},
        {"Chevron Up", ICON_FA_CHEVRON_UP},
        {"Child", ICON_FA_CHILD},
        {"Child Combatant", ICON_FA_CHILD_COMBATANT},
        {"Child Dress", ICON_FA_CHILD_DRESS},
        {"Child Reaching", ICON_FA_CHILD_REACHING},
        {"Children", ICON_FA_CHILDREN},
        {"Church", ICON_FA_CHURCH},
        {"Circle", ICON_FA_CIRCLE},
        {"Circle Arrow Down", ICON_FA_CIRCLE_ARROW_DOWN},
        {"Circle Arrow Left", ICON_FA_CIRCLE_ARROW_LEFT},
        {"Circle Arrow Right", ICON_FA_CIRCLE_ARROW_RIGHT},
        {"Circle Arrow Up", ICON_FA_CIRCLE_ARROW_UP},
        {"Circle Check", ICON_FA_CIRCLE_CHECK},
        {"Circle Chevron Down", ICON_FA_CIRCLE_CHEVRON_DOWN},
        {"Circle Chevron Left", ICON_FA_CIRCLE_CHEVRON_LEFT},
        {"Circle Chevron Right", ICON_FA_CIRCLE_CHEVRON_RIGHT},
        {"Circle Chevron Up", ICON_FA_CIRCLE_CHEVRON_UP},
        {"Circle Dollar To Slot", ICON_FA_CIRCLE_DOLLAR_TO_SLOT},
        {"Circle Dot", ICON_FA_CIRCLE_DOT},
        {"Circle Down", ICON_FA_CIRCLE_DOWN},
        {"Circle Exclamation", ICON_FA_CIRCLE_EXCLAMATION},
        {"Circle H", ICON_FA_CIRCLE_H},
        {"Circle Half Stroke", ICON_FA_CIRCLE_HALF_STROKE},
        {"Circle Info", ICON_FA_CIRCLE_INFO},
        {"Circle Left", ICON_FA_CIRCLE_LEFT},
        {"Circle Minus", ICON_FA_CIRCLE_MINUS},
        {"Circle Nodes", ICON_FA_CIRCLE_NODES},
        {"Circle Notch", ICON_FA_CIRCLE_NOTCH},
        {"Circle Pause", ICON_FA_CIRCLE_PAUSE},
        {"Circle Play", ICON_FA_CIRCLE_PLAY},
        {"Circle Plus", ICON_FA_CIRCLE_PLUS},
        {"Circle Question", ICON_FA_CIRCLE_QUESTION},
        {"Circle Radiation", ICON_FA_CIRCLE_RADIATION},
        {"Circle Right", ICON_FA_CIRCLE_RIGHT},
        {"Circle Stop", ICON_FA_CIRCLE_STOP},
        {"Circle Up", ICON_FA_CIRCLE_UP},
        {"Circle User", ICON_FA_CIRCLE_USER},
        {"Circle Xmark", ICON_FA_CIRCLE_XMARK},
        {"City", ICON_FA_CITY},
        {"Clapperboard", ICON_FA_CLAPPERBOARD},
        {"Clipboard", ICON_FA_CLIPBOARD},
        {"Clipboard Check", ICON_FA_CLIPBOARD_CHECK},
        {"Clipboard List", ICON_FA_CLIPBOARD_LIST},
        {"Clipboard Question", ICON_FA_CLIPBOARD_QUESTION},
        {"Clipboard User", ICON_FA_CLIPBOARD_USER},
        {"Clock", ICON_FA_CLOCK},
        {"Clock Rotate Left", ICON_FA_CLOCK_ROTATE_LEFT},
        {"Clone", ICON_FA_CLONE},
        {"Closed Captioning", ICON_FA_CLOSED_CAPTIONING},
        {"Cloud", ICON_FA_CLOUD},
        {"Cloud Arrow Down", ICON_FA_CLOUD_ARROW_DOWN},
        {"Cloud Arrow Up", ICON_FA_CLOUD_ARROW_UP},
        {"Cloud Bolt", ICON_FA_CLOUD_BOLT},
        {"Cloud Meatball", ICON_FA_CLOUD_MEATBALL},
        {"Cloud Moon", ICON_FA_CLOUD_MOON},
        {"Cloud Moon Rain", ICON_FA_CLOUD_MOON_RAIN},
        {"Cloud Rain", ICON_FA_CLOUD_RAIN},
        {"Cloud Showers Heavy", ICON_FA_CLOUD_SHOWERS_HEAVY},
        {"Cloud Showers Water", ICON_FA_CLOUD_SHOWERS_WATER},
        {"Cloud Sun", ICON_FA_CLOUD_SUN},
        {"Cloud Sun Rain", ICON_FA_CLOUD_SUN_RAIN},
        {"Clover", ICON_FA_CLOVER},
        {"Code", ICON_FA_CODE},
        {"Code Branch", ICON_FA_CODE_BRANCH},
        {"Code Commit", ICON_FA_CODE_COMMIT},
        {"Code Compare", ICON_FA_CODE_COMPARE},
        {"Code Fork", ICON_FA_CODE_FORK},
        {"Code Merge", ICON_FA_CODE_MERGE},
        {"Code Pull Request", ICON_FA_CODE_PULL_REQUEST},
        {"Coins", ICON_FA_COINS},
        {"Colon Sign", ICON_FA_COLON_SIGN},
        {"Comment", ICON_FA_COMMENT},
        {"Comment Dollar", ICON_FA_COMMENT_DOLLAR},
        {"Comment Dots", ICON_FA_COMMENT_DOTS},
        {"Comment Medical", ICON_FA_COMMENT_MEDICAL},
        {"Comment Nodes", ICON_FA_COMMENT_NODES},
        {"Comment Slash", ICON_FA_COMMENT_SLASH},
        {"Comment Sms", ICON_FA_COMMENT_SMS},
        {"Comments", ICON_FA_COMMENTS},
        {"Comments Dollar", ICON_FA_COMMENTS_DOLLAR},
        {"Compact Disc", ICON_FA_COMPACT_DISC},
        {"Compass", ICON_FA_COMPASS},
        {"Compass Drafting", ICON_FA_COMPASS_DRAFTING},
        {"Compress", ICON_FA_COMPRESS},
        {"Computer", ICON_FA_COMPUTER},
        {"Computer Mouse", ICON_FA_COMPUTER_MOUSE},
        {"Cookie", ICON_FA_COOKIE},
        {"Cookie Bite", ICON_FA_COOKIE_BITE},
        {"Copy", ICON_FA_COPY},
        {"Copyright", ICON_FA_COPYRIGHT},
        {"Couch", ICON_FA_COUCH},
        {"Cow", ICON_FA_COW},
        {"Credit Card", ICON_FA_CREDIT_CARD},
        {"Crop", ICON_FA_CROP},
        {"Crop Simple", ICON_FA_CROP_SIMPLE},
        {"Cross", ICON_FA_CROSS},
        {"Crosshairs", ICON_FA_CROSSHAIRS},
        {"Crow", ICON_FA_CROW},
        {"Crown", ICON_FA_CROWN},
        {"Crutch", ICON_FA_CRUTCH},
        {"Cruzeiro Sign", ICON_FA_CRUZEIRO_SIGN},
        {"Cube", ICON_FA_CUBE},
        {"Cubes", ICON_FA_CUBES},
        {"Cubes Stacked", ICON_FA_CUBES_STACKED},
        {"D", ICON_FA_D},
        {"Database", ICON_FA_DATABASE},
        {"Delete Left", ICON_FA_DELETE_LEFT},
        {"Democrat", ICON_FA_DEMOCRAT},
        {"Desktop", ICON_FA_DESKTOP},
        {"Dharmachakra", ICON_FA_DHARMACHAKRA},
        {"Diagram Next", ICON_FA_DIAGRAM_NEXT},
        {"Diagram Predecessor", ICON_FA_DIAGRAM_PREDECESSOR},
        {"Diagram Project", ICON_FA_DIAGRAM_PROJECT},
        {"Diagram Successor", ICON_FA_DIAGRAM_SUCCESSOR},
        {"Diamond", ICON_FA_DIAMOND},
        {"Diamond Turn Right", ICON_FA_DIAMOND_TURN_RIGHT},
        {"Dice", ICON_FA_DICE},
        {"Dice D20", ICON_FA_DICE_D20},
        {"Dice D6", ICON_FA_DICE_D6},
        {"Dice Five", ICON_FA_DICE_FIVE},
        {"Dice Four", ICON_FA_DICE_FOUR},
        {"Dice One", ICON_FA_DICE_ONE},
        {"Dice Six", ICON_FA_DICE_SIX},
        {"Dice Three", ICON_FA_DICE_THREE},
        {"Dice Two", ICON_FA_DICE_TWO},
        {"Disease", ICON_FA_DISEASE},
        {"Display", ICON_FA_DISPLAY},
        {"Divide", ICON_FA_DIVIDE},
        {"Dna", ICON_FA_DNA},
        {"Dog", ICON_FA_DOG},
        {"Dollar Sign", ICON_FA_DOLLAR_SIGN},
        {"Dolly", ICON_FA_DOLLY},
        {"Dong Sign", ICON_FA_DONG_SIGN},
        {"Door Closed", ICON_FA_DOOR_CLOSED},
        {"Door Open", ICON_FA_DOOR_OPEN},
        {"Dove", ICON_FA_DOVE},
        {"Down Left And Up Right To Center", ICON_FA_DOWN_LEFT_AND_UP_RIGHT_TO_CENTER},
        {"Down Long", ICON_FA_DOWN_LONG},
        {"Download", ICON_FA_DOWNLOAD},
        {"Dragon", ICON_FA_DRAGON},
        {"Draw Polygon", ICON_FA_DRAW_POLYGON},
        {"Droplet", ICON_FA_DROPLET},
        {"Droplet Slash", ICON_FA_DROPLET_SLASH},
        {"Drum", ICON_FA_DRUM},
        {"Drum Steelpan", ICON_FA_DRUM_STEELPAN},
        {"Drumstick Bite", ICON_FA_DRUMSTICK_BITE},
        {"Dumbbell", ICON_FA_DUMBBELL},
        {"Dumpster", ICON_FA_DUMPSTER},
        {"Dumpster Fire", ICON_FA_DUMPSTER_FIRE},
        {"Dungeon", ICON_FA_DUNGEON},
        {"E", ICON_FA_E},
        {"Ear Deaf", ICON_FA_EAR_DEAF},
        {"Ear Listen", ICON_FA_EAR_LISTEN},
        {"Earth Africa", ICON_FA_EARTH_AFRICA},
        {"Earth Americas", ICON_FA_EARTH_AMERICAS},
        {"Earth Asia", ICON_FA_EARTH_ASIA},
        {"Earth Europe", ICON_FA_EARTH_EUROPE},
        {"Earth Oceania", ICON_FA_EARTH_OCEANIA},
        {"Egg", ICON_FA_EGG},
        {"Eject", ICON_FA_EJECT},
        {"Elevator", ICON_FA_ELEVATOR},
        {"Ellipsis", ICON_FA_ELLIPSIS},
        {"Ellipsis Vertical", ICON_FA_ELLIPSIS_VERTICAL},
        {"Envelope", ICON_FA_ENVELOPE},
        {"Envelope Circle Check", ICON_FA_ENVELOPE_CIRCLE_CHECK},
        {"Envelope Open", ICON_FA_ENVELOPE_OPEN},
        {"Envelope Open Text", ICON_FA_ENVELOPE_OPEN_TEXT},
        {"Envelopes Bulk", ICON_FA_ENVELOPES_BULK},
        {"Equals", ICON_FA_EQUALS},
        {"Eraser", ICON_FA_ERASER},
        {"Ethernet", ICON_FA_ETHERNET},
        {"Euro Sign", ICON_FA_EURO_SIGN},
        {"Exclamation", ICON_FA_EXCLAMATION},
        {"Expand", ICON_FA_EXPAND},
        {"Explosion", ICON_FA_EXPLOSION},
        {"Eye", ICON_FA_EYE},
        {"Eye Dropper", ICON_FA_EYE_DROPPER},
        {"Eye Low Vision", ICON_FA_EYE_LOW_VISION},
        {"Eye Slash", ICON_FA_EYE_SLASH},
        {"F", ICON_FA_F},
        {"Face Angry", ICON_FA_FACE_ANGRY},
        {"Face Dizzy", ICON_FA_FACE_DIZZY},
        {"Face Flushed", ICON_FA_FACE_FLUSHED},
        {"Face Frown", ICON_FA_FACE_FROWN},
        {"Face Frown Open", ICON_FA_FACE_FROWN_OPEN},
        {"Face Grimace", ICON_FA_FACE_GRIMACE},
        {"Face Grin", ICON_FA_FACE_GRIN},
        {"Face Grin Beam", ICON_FA_FACE_GRIN_BEAM},
        {"Face Grin Beam Sweat", ICON_FA_FACE_GRIN_BEAM_SWEAT},
        {"Face Grin Hearts", ICON_FA_FACE_GRIN_HEARTS},
        {"Face Grin Squint", ICON_FA_FACE_GRIN_SQUINT},
        {"Face Grin Squint Tears", ICON_FA_FACE_GRIN_SQUINT_TEARS},
        {"Face Grin Stars", ICON_FA_FACE_GRIN_STARS},
        {"Face Grin Tears", ICON_FA_FACE_GRIN_TEARS},
        {"Face Grin Tongue", ICON_FA_FACE_GRIN_TONGUE},
        {"Face Grin Tongue Squint", ICON_FA_FACE_GRIN_TONGUE_SQUINT},
        {"Face Grin Tongue Wink", ICON_FA_FACE_GRIN_TONGUE_WINK},
        {"Face Grin Wide", ICON_FA_FACE_GRIN_WIDE},
        {"Face Grin Wink", ICON_FA_FACE_GRIN_WINK},
        {"Face Kiss", ICON_FA_FACE_KISS},
        {"Face Kiss Beam", ICON_FA_FACE_KISS_BEAM},
        {"Face Kiss Wink Heart", ICON_FA_FACE_KISS_WINK_HEART},
        {"Face Laugh", ICON_FA_FACE_LAUGH},
        {"Face Laugh Beam", ICON_FA_FACE_LAUGH_BEAM},
        {"Face Laugh Squint", ICON_FA_FACE_LAUGH_SQUINT},
        {"Face Laugh Wink", ICON_FA_FACE_LAUGH_WINK},
        {"Face Meh", ICON_FA_FACE_MEH},
        {"Face Meh Blank", ICON_FA_FACE_MEH_BLANK},
        {"Face Rolling Eyes", ICON_FA_FACE_ROLLING_EYES},
        {"Face Sad Cry", ICON_FA_FACE_SAD_CRY},
        {"Face Sad Tear", ICON_FA_FACE_SAD_TEAR},
        {"Face Smile", ICON_FA_FACE_SMILE},
        {"Face Smile Beam", ICON_FA_FACE_SMILE_BEAM},
        {"Face Smile Wink", ICON_FA_FACE_SMILE_WINK},
        {"Face Surprise", ICON_FA_FACE_SURPRISE},
        {"Face Tired", ICON_FA_FACE_TIRED},
        {"Fan", ICON_FA_FAN},
        {"Faucet", ICON_FA_FAUCET},
        {"Faucet Drip", ICON_FA_FAUCET_DRIP},
        {"Fax", ICON_FA_FAX},
        {"Feather", ICON_FA_FEATHER},
        {"Feather Pointed", ICON_FA_FEATHER_POINTED},
        {"Ferry", ICON_FA_FERRY},
        {"File", ICON_FA_FILE},
        {"File Arrow Down", ICON_FA_FILE_ARROW_DOWN},
        {"File Arrow Up", ICON_FA_FILE_ARROW_UP},
        {"File Audio", ICON_FA_FILE_AUDIO},
        {"File Circle Check", ICON_FA_FILE_CIRCLE_CHECK},
        {"File Circle Exclamation", ICON_FA_FILE_CIRCLE_EXCLAMATION},
        {"File Circle Minus", ICON_FA_FILE_CIRCLE_MINUS},
        {"File Circle Plus", ICON_FA_FILE_CIRCLE_PLUS},
        {"File Circle Question", ICON_FA_FILE_CIRCLE_QUESTION},
        {"File Circle Xmark", ICON_FA_FILE_CIRCLE_XMARK},
        {"File Code", ICON_FA_FILE_CODE},
        {"File Contract", ICON_FA_FILE_CONTRACT},
        {"File Csv", ICON_FA_FILE_CSV},
        {"File Excel", ICON_FA_FILE_EXCEL},
        {"File Export", ICON_FA_FILE_EXPORT},
        {"File Fragment", ICON_FA_FILE_FRAGMENT},
        {"File Half Dashed", ICON_FA_FILE_HALF_DASHED},
        {"File Image", ICON_FA_FILE_IMAGE},
        {"File Import", ICON_FA_FILE_IMPORT},
        {"File Invoice", ICON_FA_FILE_INVOICE},
        {"File Invoice Dollar", ICON_FA_FILE_INVOICE_DOLLAR},
        {"File Lines", ICON_FA_FILE_LINES},
        {"File Medical", ICON_FA_FILE_MEDICAL},
        {"File Pdf", ICON_FA_FILE_PDF},
        {"File Pen", ICON_FA_FILE_PEN},
        {"File Powerpoint", ICON_FA_FILE_POWERPOINT},
        {"File Prescription", ICON_FA_FILE_PRESCRIPTION},
        {"File Shield", ICON_FA_FILE_SHIELD},
        {"File Signature", ICON_FA_FILE_SIGNATURE},
        {"File Video", ICON_FA_FILE_VIDEO},
        {"File Waveform", ICON_FA_FILE_WAVEFORM},
        {"File Word", ICON_FA_FILE_WORD},
        {"File Zipper", ICON_FA_FILE_ZIPPER},
        {"Fill", ICON_FA_FILL},
        {"Fill Drip", ICON_FA_FILL_DRIP},
        {"Film", ICON_FA_FILM},
        {"Filter", ICON_FA_FILTER},
        {"Filter Circle Dollar", ICON_FA_FILTER_CIRCLE_DOLLAR},
        {"Filter Circle Xmark", ICON_FA_FILTER_CIRCLE_XMARK},
        {"Fingerprint", ICON_FA_FINGERPRINT},
        {"Fire", ICON_FA_FIRE},
        {"Fire Burner", ICON_FA_FIRE_BURNER},
        {"Fire Extinguisher", ICON_FA_FIRE_EXTINGUISHER},
        {"Fire Flame Curved", ICON_FA_FIRE_FLAME_CURVED},
        {"Fire Flame Simple", ICON_FA_FIRE_FLAME_SIMPLE},
        {"Fish", ICON_FA_FISH},
        {"Fish Fins", ICON_FA_FISH_FINS},
        {"Flag", ICON_FA_FLAG},
        {"Flag Checkered", ICON_FA_FLAG_CHECKERED},
        {"Flag Usa", ICON_FA_FLAG_USA},
        {"Flask", ICON_FA_FLASK},
        {"Flask Vial", ICON_FA_FLASK_VIAL},
        {"Floppy Disk", ICON_FA_FLOPPY_DISK},
        {"Florin Sign", ICON_FA_FLORIN_SIGN},
        {"Folder", ICON_FA_FOLDER},
        {"Folder Closed", ICON_FA_FOLDER_CLOSED},
        {"Folder Minus", ICON_FA_FOLDER_MINUS},
        {"Folder Open", ICON_FA_FOLDER_OPEN},
        {"Folder Plus", ICON_FA_FOLDER_PLUS},
        {"Folder Tree", ICON_FA_FOLDER_TREE},
        {"Font", ICON_FA_FONT},
        {"Font Awesome", ICON_FA_FONT_AWESOME},
        {"Football", ICON_FA_FOOTBALL},
        {"Forward", ICON_FA_FORWARD},
        {"Forward Fast", ICON_FA_FORWARD_FAST},
        {"Forward Step", ICON_FA_FORWARD_STEP},
        {"Franc Sign", ICON_FA_FRANC_SIGN},
        {"Frog", ICON_FA_FROG},
        {"Futbol", ICON_FA_FUTBOL},
        {"G", ICON_FA_G},
        {"Gamepad", ICON_FA_GAMEPAD},
        {"Gas Pump", ICON_FA_GAS_PUMP},
        {"Gauge", ICON_FA_GAUGE},
        {"Gauge High", ICON_FA_GAUGE_HIGH},
        {"Gauge Simple", ICON_FA_GAUGE_SIMPLE},
        {"Gauge Simple High", ICON_FA_GAUGE_SIMPLE_HIGH},
        {"Gavel", ICON_FA_GAVEL},
        {"Gear", ICON_FA_GEAR},
        {"Gears", ICON_FA_GEARS},
        {"Gem", ICON_FA_GEM},
        {"Genderless", ICON_FA_GENDERLESS},
        {"Ghost", ICON_FA_GHOST},
        {"Gift", ICON_FA_GIFT},
        {"Gifts", ICON_FA_GIFTS},
        {"Glass Water", ICON_FA_GLASS_WATER},
        {"Glass Water Droplet", ICON_FA_GLASS_WATER_DROPLET},
        {"Glasses", ICON_FA_GLASSES},
        {"Globe", ICON_FA_GLOBE},
        {"Golf Ball Tee", ICON_FA_GOLF_BALL_TEE},
        {"Gopuram", ICON_FA_GOPURAM},
        {"Graduation Cap", ICON_FA_GRADUATION_CAP},
        {"Greater Than", ICON_FA_GREATER_THAN},
        {"Greater Than Equal", ICON_FA_GREATER_THAN_EQUAL},
        {"Grip", ICON_FA_GRIP},
        {"Grip Lines", ICON_FA_GRIP_LINES},
        {"Grip Lines Vertical", ICON_FA_GRIP_LINES_VERTICAL},
        {"Grip Vertical", ICON_FA_GRIP_VERTICAL},
        {"Group Arrows Rotate", ICON_FA_GROUP_ARROWS_ROTATE},
        {"Guarani Sign", ICON_FA_GUARANI_SIGN},
        {"Guitar", ICON_FA_GUITAR},
        {"Gun", ICON_FA_GUN},
        {"H", ICON_FA_H},
        {"Hammer", ICON_FA_HAMMER},
        {"Hamsa", ICON_FA_HAMSA},
        {"Hand", ICON_FA_HAND},
        {"Hand Back Fist", ICON_FA_HAND_BACK_FIST},
        {"Hand Dots", ICON_FA_HAND_DOTS},
        {"Hand Fist", ICON_FA_HAND_FIST},
        {"Hand Holding", ICON_FA_HAND_HOLDING},
        {"Hand Holding Dollar", ICON_FA_HAND_HOLDING_DOLLAR},
        {"Hand Holding Droplet", ICON_FA_HAND_HOLDING_DROPLET},
        {"Hand Holding Hand", ICON_FA_HAND_HOLDING_HAND},
        {"Hand Holding Heart", ICON_FA_HAND_HOLDING_HEART},
        {"Hand Holding Medical", ICON_FA_HAND_HOLDING_MEDICAL},
        {"Hand Lizard", ICON_FA_HAND_LIZARD},
        {"Hand Middle Finger", ICON_FA_HAND_MIDDLE_FINGER},
        {"Hand Peace", ICON_FA_HAND_PEACE},
        {"Hand Point Down", ICON_FA_HAND_POINT_DOWN},
        {"Hand Point Left", ICON_FA_HAND_POINT_LEFT},
        {"Hand Point Right", ICON_FA_HAND_POINT_RIGHT},
        {"Hand Point Up", ICON_FA_HAND_POINT_UP},
        {"Hand Pointer", ICON_FA_HAND_POINTER},
        {"Hand Scissors", ICON_FA_HAND_SCISSORS},
        {"Hand Sparkles", ICON_FA_HAND_SPARKLES},
        {"Hand Spock", ICON_FA_HAND_SPOCK},
        {"Handcuffs", ICON_FA_HANDCUFFS},
        {"Hands", ICON_FA_HANDS},
        {"Hands Asl Interpreting", ICON_FA_HANDS_ASL_INTERPRETING},
        {"Hands Bound", ICON_FA_HANDS_BOUND},
        {"Hands Bubbles", ICON_FA_HANDS_BUBBLES},
        {"Hands Clapping", ICON_FA_HANDS_CLAPPING},
        {"Hands Holding", ICON_FA_HANDS_HOLDING},
        {"Hands Holding Child", ICON_FA_HANDS_HOLDING_CHILD},
        {"Hands Holding Circle", ICON_FA_HANDS_HOLDING_CIRCLE},
        {"Hands Praying", ICON_FA_HANDS_PRAYING},
        {"Handshake", ICON_FA_HANDSHAKE},
        {"Handshake Angle", ICON_FA_HANDSHAKE_ANGLE},
        {"Handshake Simple", ICON_FA_HANDSHAKE_SIMPLE},
        {"Handshake Simple Slash", ICON_FA_HANDSHAKE_SIMPLE_SLASH},
        {"Handshake Slash", ICON_FA_HANDSHAKE_SLASH},
        {"Hanukiah", ICON_FA_HANUKIAH},
        {"Hard Drive", ICON_FA_HARD_DRIVE},
        {"Hashtag", ICON_FA_HASHTAG},
        {"Hat Cowboy", ICON_FA_HAT_COWBOY},
        {"Hat Cowboy Side", ICON_FA_HAT_COWBOY_SIDE},
        {"Hat Wizard", ICON_FA_HAT_WIZARD},
        {"Head Side Cough", ICON_FA_HEAD_SIDE_COUGH},
        {"Head Side Cough Slash", ICON_FA_HEAD_SIDE_COUGH_SLASH},
        {"Head Side Mask", ICON_FA_HEAD_SIDE_MASK},
        {"Head Side Virus", ICON_FA_HEAD_SIDE_VIRUS},
        {"Heading", ICON_FA_HEADING},
        {"Headphones", ICON_FA_HEADPHONES},
        {"Headphones Simple", ICON_FA_HEADPHONES_SIMPLE},
        {"Headset", ICON_FA_HEADSET},
        {"Heart", ICON_FA_HEART},
        {"Heart Circle Bolt", ICON_FA_HEART_CIRCLE_BOLT},
        {"Heart Circle Check", ICON_FA_HEART_CIRCLE_CHECK},
        {"Heart Circle Exclamation", ICON_FA_HEART_CIRCLE_EXCLAMATION},
        {"Heart Circle Minus", ICON_FA_HEART_CIRCLE_MINUS},
        {"Heart Circle Plus", ICON_FA_HEART_CIRCLE_PLUS},
        {"Heart Circle Xmark", ICON_FA_HEART_CIRCLE_XMARK},
        {"Heart Crack", ICON_FA_HEART_CRACK},
        {"Heart Pulse", ICON_FA_HEART_PULSE},
        {"Helicopter", ICON_FA_HELICOPTER},
        {"Helicopter Symbol", ICON_FA_HELICOPTER_SYMBOL},
        {"Helmet Safety", ICON_FA_HELMET_SAFETY},
        {"Helmet Un", ICON_FA_HELMET_UN},
        {"Hexagon Nodes", ICON_FA_HEXAGON_NODES},
        {"Hexagon Nodes Bolt", ICON_FA_HEXAGON_NODES_BOLT},
        {"Highlighter", ICON_FA_HIGHLIGHTER},
        {"Hill Avalanche", ICON_FA_HILL_AVALANCHE},
        {"Hill Rockslide", ICON_FA_HILL_ROCKSLIDE},
        {"Hippo", ICON_FA_HIPPO},
        {"Hockey Puck", ICON_FA_HOCKEY_PUCK},
        {"Holly Berry", ICON_FA_HOLLY_BERRY},
        {"Horse", ICON_FA_HORSE},
        {"Horse Head", ICON_FA_HORSE_HEAD},
        {"Hospital", ICON_FA_HOSPITAL},
        {"Hospital User", ICON_FA_HOSPITAL_USER},
        {"Hot Tub Person", ICON_FA_HOT_TUB_PERSON},
        {"Hotdog", ICON_FA_HOTDOG},
        {"Hotel", ICON_FA_HOTEL},
        {"Hourglass", ICON_FA_HOURGLASS},
        {"Hourglass End", ICON_FA_HOURGLASS_END},
        {"Hourglass Half", ICON_FA_HOURGLASS_HALF},
        {"Hourglass Start", ICON_FA_HOURGLASS_START},
        {"House", ICON_FA_HOUSE},
        {"House Chimney", ICON_FA_HOUSE_CHIMNEY},
        {"House Chimney Crack", ICON_FA_HOUSE_CHIMNEY_CRACK},
        {"House Chimney Medical", ICON_FA_HOUSE_CHIMNEY_MEDICAL},
        {"House Chimney User", ICON_FA_HOUSE_CHIMNEY_USER},
        {"House Chimney Window", ICON_FA_HOUSE_CHIMNEY_WINDOW},
        {"House Circle Check", ICON_FA_HOUSE_CIRCLE_CHECK},
        {"House Circle Exclamation", ICON_FA_HOUSE_CIRCLE_EXCLAMATION},
        {"House Circle Xmark", ICON_FA_HOUSE_CIRCLE_XMARK},
        {"House Crack", ICON_FA_HOUSE_CRACK},
        {"House Fire", ICON_FA_HOUSE_FIRE},
        {"House Flag", ICON_FA_HOUSE_FLAG},
        {"House Flood Water", ICON_FA_HOUSE_FLOOD_WATER},
        {"House Flood Water Circle Arrow Right", ICON_FA_HOUSE_FLOOD_WATER_CIRCLE_ARROW_RIGHT},
        {"House Laptop", ICON_FA_HOUSE_LAPTOP},
        {"House Lock", ICON_FA_HOUSE_LOCK},
        {"House Medical", ICON_FA_HOUSE_MEDICAL},
        {"House Medical Circle Check", ICON_FA_HOUSE_MEDICAL_CIRCLE_CHECK},
        {"House Medical Circle Exclamation", ICON_FA_HOUSE_MEDICAL_CIRCLE_EXCLAMATION},
        {"House Medical Circle Xmark", ICON_FA_HOUSE_MEDICAL_CIRCLE_XMARK},
        {"House Medical Flag", ICON_FA_HOUSE_MEDICAL_FLAG},
        {"House Signal", ICON_FA_HOUSE_SIGNAL},
        {"House Tsunami", ICON_FA_HOUSE_TSUNAMI},
        {"House User", ICON_FA_HOUSE_USER},
        {"Hryvnia Sign", ICON_FA_HRYVNIA_SIGN},
        {"Hurricane", ICON_FA_HURRICANE},
        {"I", ICON_FA_I},
        {"I Cursor", ICON_FA_I_CURSOR},
        {"Ice Cream", ICON_FA_ICE_CREAM},
        {"Icicles", ICON_FA_ICICLES},
        {"Icons", ICON_FA_ICONS},
        {"Id Badge", ICON_FA_ID_BADGE},
        {"Id Card", ICON_FA_ID_CARD},
        {"Id Card Clip", ICON_FA_ID_CARD_CLIP},
        {"Igloo", ICON_FA_IGLOO},
        {"Image", ICON_FA_IMAGE},
        {"Image Portrait", ICON_FA_IMAGE_PORTRAIT},
        {"Images", ICON_FA_IMAGES},
        {"Inbox", ICON_FA_INBOX},
        {"Indent", ICON_FA_INDENT},
        {"Indian Rupee Sign", ICON_FA_INDIAN_RUPEE_SIGN},
        {"Industry", ICON_FA_INDUSTRY},
        {"Infinity", ICON_FA_INFINITY},
        {"Info", ICON_FA_INFO},
        {"Italic", ICON_FA_ITALIC},
        {"J", ICON_FA_J},
        {"Jar", ICON_FA_JAR},
        {"Jar Wheat", ICON_FA_JAR_WHEAT},
        {"Jedi", ICON_FA_JEDI},
        {"Jet Fighter", ICON_FA_JET_FIGHTER},
        {"Jet Fighter Up", ICON_FA_JET_FIGHTER_UP},
        {"Joint", ICON_FA_JOINT},
        {"Jug Detergent", ICON_FA_JUG_DETERGENT},
        {"K", ICON_FA_K},
        {"Kaaba", ICON_FA_KAABA},
        {"Key", ICON_FA_KEY},
        {"Keyboard", ICON_FA_KEYBOARD},
        {"Khanda", ICON_FA_KHANDA},
        {"Kip Sign", ICON_FA_KIP_SIGN},
        {"Kit Medical", ICON_FA_KIT_MEDICAL},
        {"Kitchen Set", ICON_FA_KITCHEN_SET},
        {"Kiwi Bird", ICON_FA_KIWI_BIRD},
        {"L", ICON_FA_L},
        {"Land Mine On", ICON_FA_LAND_MINE_ON},
        {"Landmark", ICON_FA_LANDMARK},
        {"Landmark Dome", ICON_FA_LANDMARK_DOME},
        {"Landmark Flag", ICON_FA_LANDMARK_FLAG},
        {"Language", ICON_FA_LANGUAGE},
        {"Laptop", ICON_FA_LAPTOP},
        {"Laptop Code", ICON_FA_LAPTOP_CODE},
        {"Laptop File", ICON_FA_LAPTOP_FILE},
        {"Laptop Medical", ICON_FA_LAPTOP_MEDICAL},
        {"Lari Sign", ICON_FA_LARI_SIGN},
        {"Layer Group", ICON_FA_LAYER_GROUP},
        {"Leaf", ICON_FA_LEAF},
        {"Left Long", ICON_FA_LEFT_LONG},
        {"Left Right", ICON_FA_LEFT_RIGHT},
        {"Lemon", ICON_FA_LEMON},
        {"Less Than", ICON_FA_LESS_THAN},
        {"Less Than Equal", ICON_FA_LESS_THAN_EQUAL},
        {"Life Ring", ICON_FA_LIFE_RING},
        {"Lightbulb", ICON_FA_LIGHTBULB},
        {"Lines Leaning", ICON_FA_LINES_LEANING},
        {"Link", ICON_FA_LINK},
        {"Link Slash", ICON_FA_LINK_SLASH},
        {"Lira Sign", ICON_FA_LIRA_SIGN},
        {"List", ICON_FA_LIST},
        {"List Check", ICON_FA_LIST_CHECK},
        {"List Ol", ICON_FA_LIST_OL},
        {"List Ul", ICON_FA_LIST_UL},
        {"Litecoin Sign", ICON_FA_LITECOIN_SIGN},
        {"Location Arrow", ICON_FA_LOCATION_ARROW},
        {"Location Crosshairs", ICON_FA_LOCATION_CROSSHAIRS},
        {"Location Dot", ICON_FA_LOCATION_DOT},
        {"Location Pin", ICON_FA_LOCATION_PIN},
        {"Location Pin Lock", ICON_FA_LOCATION_PIN_LOCK},
        {"Lock", ICON_FA_LOCK},
        {"Lock Open", ICON_FA_LOCK_OPEN},
        {"Locust", ICON_FA_LOCUST},
        {"Lungs", ICON_FA_LUNGS},
        {"Lungs Virus", ICON_FA_LUNGS_VIRUS},
        {"M", ICON_FA_M},
        {"Magnet", ICON_FA_MAGNET},
        {"Magnifying Glass", ICON_FA_MAGNIFYING_GLASS},
        {"Magnifying Glass Arrow Right", ICON_FA_MAGNIFYING_GLASS_ARROW_RIGHT},
        {"Magnifying Glass Chart", ICON_FA_MAGNIFYING_GLASS_CHART},
        {"Magnifying Glass Dollar", ICON_FA_MAGNIFYING_GLASS_DOLLAR},
        {"Magnifying Glass Location", ICON_FA_MAGNIFYING_GLASS_LOCATION},
        {"Magnifying Glass Minus", ICON_FA_MAGNIFYING_GLASS_MINUS},
        {"Magnifying Glass Plus", ICON_FA_MAGNIFYING_GLASS_PLUS},
        {"Manat Sign", ICON_FA_MANAT_SIGN},
        {"Map", ICON_FA_MAP},
        {"Map Location", ICON_FA_MAP_LOCATION},
        {"Map Location Dot", ICON_FA_MAP_LOCATION_DOT},
        {"Map Pin", ICON_FA_MAP_PIN},
        {"Marker", ICON_FA_MARKER},
        {"Mars", ICON_FA_MARS},
        {"Mars And Venus", ICON_FA_MARS_AND_VENUS},
        {"Mars And Venus Burst", ICON_FA_MARS_AND_VENUS_BURST},
        {"Mars Double", ICON_FA_MARS_DOUBLE},
        {"Mars Stroke", ICON_FA_MARS_STROKE},
        {"Mars Stroke Right", ICON_FA_MARS_STROKE_RIGHT},
        {"Mars Stroke Up", ICON_FA_MARS_STROKE_UP},
        {"Martini Glass", ICON_FA_MARTINI_GLASS},
        {"Martini Glass Citrus", ICON_FA_MARTINI_GLASS_CITRUS},
        {"Martini Glass Empty", ICON_FA_MARTINI_GLASS_EMPTY},
        {"Mask", ICON_FA_MASK},
        {"Mask Face", ICON_FA_MASK_FACE},
        {"Mask Ventilator", ICON_FA_MASK_VENTILATOR},
        {"Masks Theater", ICON_FA_MASKS_THEATER},
        {"Mattress Pillow", ICON_FA_MATTRESS_PILLOW},
        {"Maximize", ICON_FA_MAXIMIZE},
        {"Medal", ICON_FA_MEDAL},
        {"Memory", ICON_FA_MEMORY},
        {"Menorah", ICON_FA_MENORAH},
        {"Mercury", ICON_FA_MERCURY},
        {"Message", ICON_FA_MESSAGE},
        {"Meteor", ICON_FA_METEOR},
        {"Microchip", ICON_FA_MICROCHIP},
        {"Microphone", ICON_FA_MICROPHONE},
        {"Microphone Lines", ICON_FA_MICROPHONE_LINES},
        {"Microphone Lines Slash", ICON_FA_MICROPHONE_LINES_SLASH},
        {"Microphone Slash", ICON_FA_MICROPHONE_SLASH},
        {"Microscope", ICON_FA_MICROSCOPE},
        {"Mill Sign", ICON_FA_MILL_SIGN},
        {"Minimize", ICON_FA_MINIMIZE},
        {"Minus", ICON_FA_MINUS},
        {"Mitten", ICON_FA_MITTEN},
        {"Mobile", ICON_FA_MOBILE},
        {"Mobile Button", ICON_FA_MOBILE_BUTTON},
        {"Mobile Retro", ICON_FA_MOBILE_RETRO},
        {"Mobile Screen", ICON_FA_MOBILE_SCREEN},
        {"Mobile Screen Button", ICON_FA_MOBILE_SCREEN_BUTTON},
        {"Money Bill", ICON_FA_MONEY_BILL},
        {"Money Bill 1", ICON_FA_MONEY_BILL_1},
        {"Money Bill 1 Wave", ICON_FA_MONEY_BILL_1_WAVE},
        {"Money Bill Transfer", ICON_FA_MONEY_BILL_TRANSFER},
        {"Money Bill Trend Up", ICON_FA_MONEY_BILL_TREND_UP},
        {"Money Bill Wave", ICON_FA_MONEY_BILL_WAVE},
        {"Money Bill Wheat", ICON_FA_MONEY_BILL_WHEAT},
        {"Money Bills", ICON_FA_MONEY_BILLS},
        {"Money Check", ICON_FA_MONEY_CHECK},
        {"Money Check Dollar", ICON_FA_MONEY_CHECK_DOLLAR},
        {"Monument", ICON_FA_MONUMENT},
        {"Moon", ICON_FA_MOON},
        {"Mortar Pestle", ICON_FA_MORTAR_PESTLE},
        {"Mosque", ICON_FA_MOSQUE},
        {"Mosquito", ICON_FA_MOSQUITO},
        {"Mosquito Net", ICON_FA_MOSQUITO_NET},
        {"Motorcycle", ICON_FA_MOTORCYCLE},
        {"Mound", ICON_FA_MOUND},
        {"Mountain", ICON_FA_MOUNTAIN},
        {"Mountain City", ICON_FA_MOUNTAIN_CITY},
        {"Mountain Sun", ICON_FA_MOUNTAIN_SUN},
        {"Mug Hot", ICON_FA_MUG_HOT},
        {"Mug Saucer", ICON_FA_MUG_SAUCER},
        {"Music", ICON_FA_MUSIC},
        {"N", ICON_FA_N},
        {"Naira Sign", ICON_FA_NAIRA_SIGN},
        {"Network Wired", ICON_FA_NETWORK_WIRED},
        {"Neuter", ICON_FA_NEUTER},
        {"Newspaper", ICON_FA_NEWSPAPER},
        {"Not Equal", ICON_FA_NOT_EQUAL},
        {"Notdef", ICON_FA_NOTDEF},
        {"Note Sticky", ICON_FA_NOTE_STICKY},
        {"Notes Medical", ICON_FA_NOTES_MEDICAL},
        {"O", ICON_FA_O},
        {"Object Group", ICON_FA_OBJECT_GROUP},
        {"Object Ungroup", ICON_FA_OBJECT_UNGROUP},
        {"Oil Can", ICON_FA_OIL_CAN},
        {"Oil Well", ICON_FA_OIL_WELL},
        {"Om", ICON_FA_OM},
        {"Otter", ICON_FA_OTTER},
        {"Outdent", ICON_FA_OUTDENT},
        {"P", ICON_FA_P},
        {"Pager", ICON_FA_PAGER},
        {"Paint Roller", ICON_FA_PAINT_ROLLER},
        {"Paintbrush", ICON_FA_PAINTBRUSH},
        {"Palette", ICON_FA_PALETTE},
        {"Pallet", ICON_FA_PALLET},
        {"Panorama", ICON_FA_PANORAMA},
        {"Paper Plane", ICON_FA_PAPER_PLANE},
        {"Paperclip", ICON_FA_PAPERCLIP},
        {"Parachute Box", ICON_FA_PARACHUTE_BOX},
        {"Paragraph", ICON_FA_PARAGRAPH},
        {"Passport", ICON_FA_PASSPORT},
        {"Paste", ICON_FA_PASTE},
        {"Pause", ICON_FA_PAUSE},
        {"Paw", ICON_FA_PAW},
        {"Peace", ICON_FA_PEACE},
        {"Pen", ICON_FA_PEN},
        {"Pen Clip", ICON_FA_PEN_CLIP},
        {"Pen Fancy", ICON_FA_PEN_FANCY},
        {"Pen Nib", ICON_FA_PEN_NIB},
        {"Pen Ruler", ICON_FA_PEN_RULER},
        {"Pen To Square", ICON_FA_PEN_TO_SQUARE},
        {"Pencil", ICON_FA_PENCIL},
        {"People Arrows", ICON_FA_PEOPLE_ARROWS},
        {"People Carry Box", ICON_FA_PEOPLE_CARRY_BOX},
        {"People Group", ICON_FA_PEOPLE_GROUP},
        {"People Line", ICON_FA_PEOPLE_LINE},
        {"People Pulling", ICON_FA_PEOPLE_PULLING},
        {"People Robbery", ICON_FA_PEOPLE_ROBBERY},
        {"People Roof", ICON_FA_PEOPLE_ROOF},
        {"Pepper Hot", ICON_FA_PEPPER_HOT},
        {"Percent", ICON_FA_PERCENT},
        {"Person", ICON_FA_PERSON},
        {"Person Arrow Down To Line", ICON_FA_PERSON_ARROW_DOWN_TO_LINE},
        {"Person Arrow Up From Line", ICON_FA_PERSON_ARROW_UP_FROM_LINE},
        {"Person Biking", ICON_FA_PERSON_BIKING},
        {"Person Booth", ICON_FA_PERSON_BOOTH},
        {"Person Breastfeeding", ICON_FA_PERSON_BREASTFEEDING},
        {"Person Burst", ICON_FA_PERSON_BURST},
        {"Person Cane", ICON_FA_PERSON_CANE},
        {"Person Chalkboard", ICON_FA_PERSON_CHALKBOARD},
        {"Person Circle Check", ICON_FA_PERSON_CIRCLE_CHECK},
        {"Person Circle Exclamation", ICON_FA_PERSON_CIRCLE_EXCLAMATION},
        {"Person Circle Minus", ICON_FA_PERSON_CIRCLE_MINUS},
        {"Person Circle Plus", ICON_FA_PERSON_CIRCLE_PLUS},
        {"Person Circle Question", ICON_FA_PERSON_CIRCLE_QUESTION},
        {"Person Circle Xmark", ICON_FA_PERSON_CIRCLE_XMARK},
        {"Person Digging", ICON_FA_PERSON_DIGGING},
        {"Person Dots From Line", ICON_FA_PERSON_DOTS_FROM_LINE},
        {"Person Dress", ICON_FA_PERSON_DRESS},
        {"Person Dress Burst", ICON_FA_PERSON_DRESS_BURST},
        {"Person Drowning", ICON_FA_PERSON_DROWNING},
        {"Person Falling", ICON_FA_PERSON_FALLING},
        {"Person Falling Burst", ICON_FA_PERSON_FALLING_BURST},
        {"Person Half Dress", ICON_FA_PERSON_HALF_DRESS},
        {"Person Harassing", ICON_FA_PERSON_HARASSING},
        {"Person Hiking", ICON_FA_PERSON_HIKING},
        {"Person Military Pointing", ICON_FA_PERSON_MILITARY_POINTING},
        {"Person Military Rifle", ICON_FA_PERSON_MILITARY_RIFLE},
        {"Person Military To Person", ICON_FA_PERSON_MILITARY_TO_PERSON},
        {"Person Praying", ICON_FA_PERSON_PRAYING},
        {"Person Pregnant", ICON_FA_PERSON_PREGNANT},
        {"Person Rays", ICON_FA_PERSON_RAYS},
        {"Person Rifle", ICON_FA_PERSON_RIFLE},
        {"Person Running", ICON_FA_PERSON_RUNNING},
        {"Person Shelter", ICON_FA_PERSON_SHELTER},
        {"Person Skating", ICON_FA_PERSON_SKATING},
        {"Person Skiing", ICON_FA_PERSON_SKIING},
        {"Person Skiing Nordic", ICON_FA_PERSON_SKIING_NORDIC},
        {"Person Snowboarding", ICON_FA_PERSON_SNOWBOARDING},
        {"Person Swimming", ICON_FA_PERSON_SWIMMING},
        {"Person Through Window", ICON_FA_PERSON_THROUGH_WINDOW},
        {"Person Walking", ICON_FA_PERSON_WALKING},
        {"Person Walking Arrow Loop Left", ICON_FA_PERSON_WALKING_ARROW_LOOP_LEFT},
        {"Person Walking Arrow Right", ICON_FA_PERSON_WALKING_ARROW_RIGHT},
        {"Person Walking Dashed Line Arrow Right", ICON_FA_PERSON_WALKING_DASHED_LINE_ARROW_RIGHT},
        {"Person Walking Luggage", ICON_FA_PERSON_WALKING_LUGGAGE},
        {"Person Walking With Cane", ICON_FA_PERSON_WALKING_WITH_CANE},
        {"Peseta Sign", ICON_FA_PESETA_SIGN},
        {"Peso Sign", ICON_FA_PESO_SIGN},
        {"Phone", ICON_FA_PHONE},
        {"Phone Flip", ICON_FA_PHONE_FLIP},
        {"Phone Slash", ICON_FA_PHONE_SLASH},
        {"Phone Volume", ICON_FA_PHONE_VOLUME},
        {"Photo Film", ICON_FA_PHOTO_FILM},
        {"Piggy Bank", ICON_FA_PIGGY_BANK},
        {"Pills", ICON_FA_PILLS},
        {"Pizza Slice", ICON_FA_PIZZA_SLICE},
        {"Place Of Worship", ICON_FA_PLACE_OF_WORSHIP},
        {"Plane", ICON_FA_PLANE},
        {"Plane Arrival", ICON_FA_PLANE_ARRIVAL},
        {"Plane Circle Check", ICON_FA_PLANE_CIRCLE_CHECK},
        {"Plane Circle Exclamation", ICON_FA_PLANE_CIRCLE_EXCLAMATION},
        {"Plane Circle Xmark", ICON_FA_PLANE_CIRCLE_XMARK},
        {"Plane Departure", ICON_FA_PLANE_DEPARTURE},
        {"Plane Lock", ICON_FA_PLANE_LOCK},
        {"Plane Slash", ICON_FA_PLANE_SLASH},
        {"Plane Up", ICON_FA_PLANE_UP},
        {"Plant Wilt", ICON_FA_PLANT_WILT},
        {"Plate Wheat", ICON_FA_PLATE_WHEAT},
        {"Play", ICON_FA_PLAY},
        {"Plug", ICON_FA_PLUG},
        {"Plug Circle Bolt", ICON_FA_PLUG_CIRCLE_BOLT},
        {"Plug Circle Check", ICON_FA_PLUG_CIRCLE_CHECK},
        {"Plug Circle Exclamation", ICON_FA_PLUG_CIRCLE_EXCLAMATION},
        {"Plug Circle Minus", ICON_FA_PLUG_CIRCLE_MINUS},
        {"Plug Circle Plus", ICON_FA_PLUG_CIRCLE_PLUS},
        {"Plug Circle Xmark", ICON_FA_PLUG_CIRCLE_XMARK},
        {"Plus", ICON_FA_PLUS},
        {"Plus Minus", ICON_FA_PLUS_MINUS},
        {"Podcast", ICON_FA_PODCAST},
        {"Poo", ICON_FA_POO},
        {"Poo Storm", ICON_FA_POO_STORM},
        {"Poop", ICON_FA_POOP},
        {"Power Off", ICON_FA_POWER_OFF},
        {"Prescription", ICON_FA_PRESCRIPTION},
        {"Prescription Bottle", ICON_FA_PRESCRIPTION_BOTTLE},
        {"Prescription Bottle Medical", ICON_FA_PRESCRIPTION_BOTTLE_MEDICAL},
        {"Print", ICON_FA_PRINT},
        {"Pump Medical", ICON_FA_PUMP_MEDICAL},
        {"Pump Soap", ICON_FA_PUMP_SOAP},
        {"Puzzle Piece", ICON_FA_PUZZLE_PIECE},
        {"Q", ICON_FA_Q},
        {"Qrcode", ICON_FA_QRCODE},
        {"Question", ICON_FA_QUESTION},
        {"Quote Left", ICON_FA_QUOTE_LEFT},
        {"Quote Right", ICON_FA_QUOTE_RIGHT},
        {"R", ICON_FA_R},
        {"Radiation", ICON_FA_RADIATION},
        {"Radio", ICON_FA_RADIO},
        {"Rainbow", ICON_FA_RAINBOW},
        {"Ranking Star", ICON_FA_RANKING_STAR},
        {"Receipt", ICON_FA_RECEIPT},
        {"Record Vinyl", ICON_FA_RECORD_VINYL},
        {"Rectangle Ad", ICON_FA_RECTANGLE_AD},
        {"Rectangle List", ICON_FA_RECTANGLE_LIST},
        {"Rectangle Xmark", ICON_FA_RECTANGLE_XMARK},
        {"Recycle", ICON_FA_RECYCLE},
        {"Registered", ICON_FA_REGISTERED},
        {"Repeat", ICON_FA_REPEAT},
        {"Reply", ICON_FA_REPLY},
        {"Reply All", ICON_FA_REPLY_ALL},
        {"Republican", ICON_FA_REPUBLICAN},
        {"Restroom", ICON_FA_RESTROOM},
        {"Retweet", ICON_FA_RETWEET},
        {"Ribbon", ICON_FA_RIBBON},
        {"Right From Bracket", ICON_FA_RIGHT_FROM_BRACKET},
        {"Right Left", ICON_FA_RIGHT_LEFT},
        {"Right Long", ICON_FA_RIGHT_LONG},
        {"Right To Bracket", ICON_FA_RIGHT_TO_BRACKET},
        {"Ring", ICON_FA_RING},
        {"Road", ICON_FA_ROAD},
        {"Road Barrier", ICON_FA_ROAD_BARRIER},
        {"Road Bridge", ICON_FA_ROAD_BRIDGE},
        {"Road Circle Check", ICON_FA_ROAD_CIRCLE_CHECK},
        {"Road Circle Exclamation", ICON_FA_ROAD_CIRCLE_EXCLAMATION},
        {"Road Circle Xmark", ICON_FA_ROAD_CIRCLE_XMARK},
        {"Road Lock", ICON_FA_ROAD_LOCK},
        {"Road Spikes", ICON_FA_ROAD_SPIKES},
        {"Robot", ICON_FA_ROBOT},
        {"Rocket", ICON_FA_ROCKET},
        {"Rotate", ICON_FA_ROTATE},
        {"Rotate Left", ICON_FA_ROTATE_LEFT},
        {"Rotate Right", ICON_FA_ROTATE_RIGHT},
        {"Route", ICON_FA_ROUTE},
        {"Rss", ICON_FA_RSS},
        {"Ruble Sign", ICON_FA_RUBLE_SIGN},
        {"Rug", ICON_FA_RUG},
        {"Ruler", ICON_FA_RULER},
        {"Ruler Combined", ICON_FA_RULER_COMBINED},
        {"Ruler Horizontal", ICON_FA_RULER_HORIZONTAL},
        {"Ruler Vertical", ICON_FA_RULER_VERTICAL},
        {"Rupee Sign", ICON_FA_RUPEE_SIGN},
        {"Rupiah Sign", ICON_FA_RUPIAH_SIGN},
        {"S", ICON_FA_S},
        {"Sack Dollar", ICON_FA_SACK_DOLLAR},
        {"Sack Xmark", ICON_FA_SACK_XMARK},
        {"Sailboat", ICON_FA_SAILBOAT},
        {"Satellite", ICON_FA_SATELLITE},
        {"Satellite Dish", ICON_FA_SATELLITE_DISH},
        {"Scale Balanced", ICON_FA_SCALE_BALANCED},
        {"Scale Unbalanced", ICON_FA_SCALE_UNBALANCED},
        {"Scale Unbalanced Flip", ICON_FA_SCALE_UNBALANCED_FLIP},
        {"School", ICON_FA_SCHOOL},
        {"School Circle Check", ICON_FA_SCHOOL_CIRCLE_CHECK},
        {"School Circle Exclamation", ICON_FA_SCHOOL_CIRCLE_EXCLAMATION},
        {"School Circle Xmark", ICON_FA_SCHOOL_CIRCLE_XMARK},
        {"School Flag", ICON_FA_SCHOOL_FLAG},
        {"School Lock", ICON_FA_SCHOOL_LOCK},
        {"Scissors", ICON_FA_SCISSORS},
        {"Screwdriver", ICON_FA_SCREWDRIVER},
        {"Screwdriver Wrench", ICON_FA_SCREWDRIVER_WRENCH},
        {"Scroll", ICON_FA_SCROLL},
        {"Scroll Torah", ICON_FA_SCROLL_TORAH},
        {"Sd Card", ICON_FA_SD_CARD},
        {"Section", ICON_FA_SECTION},
        {"Seedling", ICON_FA_SEEDLING},
        {"Server", ICON_FA_SERVER},
        {"Shapes", ICON_FA_SHAPES},
        {"Share", ICON_FA_SHARE},
        {"Share From Square", ICON_FA_SHARE_FROM_SQUARE},
        {"Share Nodes", ICON_FA_SHARE_NODES},
        {"Sheet Plastic", ICON_FA_SHEET_PLASTIC},
        {"Shekel Sign", ICON_FA_SHEKEL_SIGN},
        {"Shield", ICON_FA_SHIELD},
        {"Shield Cat", ICON_FA_SHIELD_CAT},
        {"Shield Dog", ICON_FA_SHIELD_DOG},
        {"Shield Halved", ICON_FA_SHIELD_HALVED},
        {"Shield Heart", ICON_FA_SHIELD_HEART},
        {"Shield Virus", ICON_FA_SHIELD_VIRUS},
        {"Ship", ICON_FA_SHIP},
        {"Shirt", ICON_FA_SHIRT},
        {"Shoe Prints", ICON_FA_SHOE_PRINTS},
        {"Shop", ICON_FA_SHOP},
        {"Shop Lock", ICON_FA_SHOP_LOCK},
        {"Shop Slash", ICON_FA_SHOP_SLASH},
        {"Shower", ICON_FA_SHOWER},
        {"Shrimp", ICON_FA_SHRIMP},
        {"Shuffle", ICON_FA_SHUFFLE},
        {"Shuttle Space", ICON_FA_SHUTTLE_SPACE},
        {"Sign Hanging", ICON_FA_SIGN_HANGING},
        {"Signal", ICON_FA_SIGNAL},
        {"Signature", ICON_FA_SIGNATURE},
        {"Signs Post", ICON_FA_SIGNS_POST},
        {"Sim Card", ICON_FA_SIM_CARD},
        {"Sink", ICON_FA_SINK},
        {"Sitemap", ICON_FA_SITEMAP},
        {"Skull", ICON_FA_SKULL},
        {"Skull Crossbones", ICON_FA_SKULL_CROSSBONES},
        {"Slash", ICON_FA_SLASH},
        {"Sleigh", ICON_FA_SLEIGH},
        {"Sliders", ICON_FA_SLIDERS},
        {"Smog", ICON_FA_SMOG},
        {"Smoking", ICON_FA_SMOKING},
        {"Snowflake", ICON_FA_SNOWFLAKE},
        {"Snowman", ICON_FA_SNOWMAN},
        {"Snowplow", ICON_FA_SNOWPLOW},
        {"Soap", ICON_FA_SOAP},
        {"Socks", ICON_FA_SOCKS},
        {"Solar Panel", ICON_FA_SOLAR_PANEL},
        {"Sort", ICON_FA_SORT},
        {"Sort Down", ICON_FA_SORT_DOWN},
        {"Sort Up", ICON_FA_SORT_UP},
        {"Spa", ICON_FA_SPA},
        {"Spaghetti Monster Flying", ICON_FA_SPAGHETTI_MONSTER_FLYING},
        {"Spell Check", ICON_FA_SPELL_CHECK},
        {"Spider", ICON_FA_SPIDER},
        {"Spinner", ICON_FA_SPINNER},
        {"Splotch", ICON_FA_SPLOTCH},
        {"Spoon", ICON_FA_SPOON},
        {"Spray Can", ICON_FA_SPRAY_CAN},
        {"Spray Can Sparkles", ICON_FA_SPRAY_CAN_SPARKLES},
        {"Square", ICON_FA_SQUARE},
        {"Square Arrow Up Right", ICON_FA_SQUARE_ARROW_UP_RIGHT},
        {"Square Binary", ICON_FA_SQUARE_BINARY},
        {"Square Caret Down", ICON_FA_SQUARE_CARET_DOWN},
        {"Square Caret Left", ICON_FA_SQUARE_CARET_LEFT},
        {"Square Caret Right", ICON_FA_SQUARE_CARET_RIGHT},
        {"Square Caret Up", ICON_FA_SQUARE_CARET_UP},
        {"Square Check", ICON_FA_SQUARE_CHECK},
        {"Square Envelope", ICON_FA_SQUARE_ENVELOPE},
        {"Square Full", ICON_FA_SQUARE_FULL},
        {"Square H", ICON_FA_SQUARE_H},
        {"Square Minus", ICON_FA_SQUARE_MINUS},
        {"Square Nfi", ICON_FA_SQUARE_NFI},
        {"Square Parking", ICON_FA_SQUARE_PARKING},
        {"Square Pen", ICON_FA_SQUARE_PEN},
        {"Square Person Confined", ICON_FA_SQUARE_PERSON_CONFINED},
        {"Square Phone", ICON_FA_SQUARE_PHONE},
        {"Square Phone Flip", ICON_FA_SQUARE_PHONE_FLIP},
        {"Square Plus", ICON_FA_SQUARE_PLUS},
        {"Square Poll Horizontal", ICON_FA_SQUARE_POLL_HORIZONTAL},
        {"Square Poll Vertical", ICON_FA_SQUARE_POLL_VERTICAL},
        {"Square Root Variable", ICON_FA_SQUARE_ROOT_VARIABLE},
        {"Square Rss", ICON_FA_SQUARE_RSS},
        {"Square Share Nodes", ICON_FA_SQUARE_SHARE_NODES},
        {"Square Up Right", ICON_FA_SQUARE_UP_RIGHT},
        {"Square Virus", ICON_FA_SQUARE_VIRUS},
        {"Square Xmark", ICON_FA_SQUARE_XMARK},
        {"Staff Snake", ICON_FA_STAFF_SNAKE},
        {"Stairs", ICON_FA_STAIRS},
        {"Stamp", ICON_FA_STAMP},
        {"Stapler", ICON_FA_STAPLER},
        {"Star", ICON_FA_STAR},
        {"Star And Crescent", ICON_FA_STAR_AND_CRESCENT},
        {"Star Half", ICON_FA_STAR_HALF},
        {"Star Half Stroke", ICON_FA_STAR_HALF_STROKE},
        {"Star Of David", ICON_FA_STAR_OF_DAVID},
        {"Star Of Life", ICON_FA_STAR_OF_LIFE},
        {"Sterling Sign", ICON_FA_STERLING_SIGN},
        {"Stethoscope", ICON_FA_STETHOSCOPE},
        {"Stop", ICON_FA_STOP},
        {"Stopwatch", ICON_FA_STOPWATCH},
        {"Stopwatch 20", ICON_FA_STOPWATCH_20},
        {"Store", ICON_FA_STORE},
        {"Store Slash", ICON_FA_STORE_SLASH},
        {"Street View", ICON_FA_STREET_VIEW},
        {"Strikethrough", ICON_FA_STRIKETHROUGH},
        {"Stroopwafel", ICON_FA_STROOPWAFEL},
        {"Subscript", ICON_FA_SUBSCRIPT},
        {"Suitcase", ICON_FA_SUITCASE},
        {"Suitcase Medical", ICON_FA_SUITCASE_MEDICAL},
        {"Suitcase Rolling", ICON_FA_SUITCASE_ROLLING},
        {"Sun", ICON_FA_SUN},
        {"Sun Plant Wilt", ICON_FA_SUN_PLANT_WILT},
        {"Superscript", ICON_FA_SUPERSCRIPT},
        {"Swatchbook", ICON_FA_SWATCHBOOK},
        {"Synagogue", ICON_FA_SYNAGOGUE},
        {"Syringe", ICON_FA_SYRINGE},
        {"T", ICON_FA_T},
        {"Table", ICON_FA_TABLE},
        {"Table Cells", ICON_FA_TABLE_CELLS},
        {"Table Cells Column Lock", ICON_FA_TABLE_CELLS_COLUMN_LOCK},
        {"Table Cells Large", ICON_FA_TABLE_CELLS_LARGE},
        {"Table Cells Row Lock", ICON_FA_TABLE_CELLS_ROW_LOCK},
        {"Table Cells Row Unlock", ICON_FA_TABLE_CELLS_ROW_UNLOCK},
        {"Table Columns", ICON_FA_TABLE_COLUMNS},
        {"Table List", ICON_FA_TABLE_LIST},
        {"Table Tennis Paddle Ball", ICON_FA_TABLE_TENNIS_PADDLE_BALL},
        {"Tablet", ICON_FA_TABLET},
        {"Tablet Button", ICON_FA_TABLET_BUTTON},
        {"Tablet Screen Button", ICON_FA_TABLET_SCREEN_BUTTON},
        {"Tablets", ICON_FA_TABLETS},
        {"Tachograph Digital", ICON_FA_TACHOGRAPH_DIGITAL},
        {"Tag", ICON_FA_TAG},
        {"Tags", ICON_FA_TAGS},
        {"Tape", ICON_FA_TAPE},
        {"Tarp", ICON_FA_TARP},
        {"Tarp Droplet", ICON_FA_TARP_DROPLET},
        {"Taxi", ICON_FA_TAXI},
        {"Teeth", ICON_FA_TEETH},
        {"Teeth Open", ICON_FA_TEETH_OPEN},
        {"Temperature Arrow Down", ICON_FA_TEMPERATURE_ARROW_DOWN},
        {"Temperature Arrow Up", ICON_FA_TEMPERATURE_ARROW_UP},
        {"Temperature Empty", ICON_FA_TEMPERATURE_EMPTY},
        {"Temperature Full", ICON_FA_TEMPERATURE_FULL},
        {"Temperature Half", ICON_FA_TEMPERATURE_HALF},
        {"Temperature High", ICON_FA_TEMPERATURE_HIGH},
        {"Temperature Low", ICON_FA_TEMPERATURE_LOW},
        {"Temperature Quarter", ICON_FA_TEMPERATURE_QUARTER},
        {"Temperature Three Quarters", ICON_FA_TEMPERATURE_THREE_QUARTERS},
        {"Tenge Sign", ICON_FA_TENGE_SIGN},
        {"Tent", ICON_FA_TENT},
        {"Tent Arrow Down To Line", ICON_FA_TENT_ARROW_DOWN_TO_LINE},
        {"Tent Arrow Left Right", ICON_FA_TENT_ARROW_LEFT_RIGHT},
        {"Tent Arrow Turn Left", ICON_FA_TENT_ARROW_TURN_LEFT},
        {"Tent Arrows Down", ICON_FA_TENT_ARROWS_DOWN},
        {"Tents", ICON_FA_TENTS},
        {"Terminal", ICON_FA_TERMINAL},
        {"Text Height", ICON_FA_TEXT_HEIGHT},
        {"Text Slash", ICON_FA_TEXT_SLASH},
        {"Text Width", ICON_FA_TEXT_WIDTH},
        {"Thermometer", ICON_FA_THERMOMETER},
        {"Thumbs Down", ICON_FA_THUMBS_DOWN},
        {"Thumbs Up", ICON_FA_THUMBS_UP},
        {"Thumbtack", ICON_FA_THUMBTACK},
        {"Thumbtack Slash", ICON_FA_THUMBTACK_SLASH},
        {"Ticket", ICON_FA_TICKET},
        {"Ticket Simple", ICON_FA_TICKET_SIMPLE},
        {"Timeline", ICON_FA_TIMELINE},
        {"Toggle Off", ICON_FA_TOGGLE_OFF},
        {"Toggle On", ICON_FA_TOGGLE_ON},
        {"Toilet", ICON_FA_TOILET},
        {"Toilet Paper", ICON_FA_TOILET_PAPER},
        {"Toilet Paper Slash", ICON_FA_TOILET_PAPER_SLASH},
        {"Toilet Portable", ICON_FA_TOILET_PORTABLE},
        {"Toilets Portable", ICON_FA_TOILETS_PORTABLE},
        {"Toolbox", ICON_FA_TOOLBOX},
        {"Tooth", ICON_FA_TOOTH},
        {"Torii Gate", ICON_FA_TORII_GATE},
        {"Tornado", ICON_FA_TORNADO},
        {"Tower Broadcast", ICON_FA_TOWER_BROADCAST},
        {"Tower Cell", ICON_FA_TOWER_CELL},
        {"Tower Observation", ICON_FA_TOWER_OBSERVATION},
        {"Tractor", ICON_FA_TRACTOR},
        {"Trademark", ICON_FA_TRADEMARK},
        {"Traffic Light", ICON_FA_TRAFFIC_LIGHT},
        {"Trailer", ICON_FA_TRAILER},
        {"Train", ICON_FA_TRAIN},
        {"Train Subway", ICON_FA_TRAIN_SUBWAY},
        {"Train Tram", ICON_FA_TRAIN_TRAM},
        {"Transgender", ICON_FA_TRANSGENDER},
        {"Trash", ICON_FA_TRASH},
        {"Trash Arrow Up", ICON_FA_TRASH_ARROW_UP},
        {"Trash Can", ICON_FA_TRASH_CAN},
        {"Trash Can Arrow Up", ICON_FA_TRASH_CAN_ARROW_UP},
        {"Tree", ICON_FA_TREE},
        {"Tree City", ICON_FA_TREE_CITY},
        {"Triangle Exclamation", ICON_FA_TRIANGLE_EXCLAMATION},
        {"Trophy", ICON_FA_TROPHY},
        {"Trowel", ICON_FA_TROWEL},
        {"Trowel Bricks", ICON_FA_TROWEL_BRICKS},
        {"Truck", ICON_FA_TRUCK},
        {"Truck Arrow Right", ICON_FA_TRUCK_ARROW_RIGHT},
        {"Truck Droplet", ICON_FA_TRUCK_DROPLET},
        {"Truck Fast", ICON_FA_TRUCK_FAST},
        {"Truck Field", ICON_FA_TRUCK_FIELD},
        {"Truck Field Un", ICON_FA_TRUCK_FIELD_UN},
        {"Truck Front", ICON_FA_TRUCK_FRONT},
        {"Truck Medical", ICON_FA_TRUCK_MEDICAL},
        {"Truck Monster", ICON_FA_TRUCK_MONSTER},
        {"Truck Moving", ICON_FA_TRUCK_MOVING},
        {"Truck Pickup", ICON_FA_TRUCK_PICKUP},
        {"Truck Plane", ICON_FA_TRUCK_PLANE},
        {"Truck Ramp Box", ICON_FA_TRUCK_RAMP_BOX},
        {"Tty", ICON_FA_TTY},
        {"Turkish Lira Sign", ICON_FA_TURKISH_LIRA_SIGN},
        {"Turn Down", ICON_FA_TURN_DOWN},
        {"Turn Up", ICON_FA_TURN_UP},
        {"Tv", ICON_FA_TV},
        {"U", ICON_FA_U},
        {"Umbrella", ICON_FA_UMBRELLA},
        {"Umbrella Beach", ICON_FA_UMBRELLA_BEACH},
        {"Underline", ICON_FA_UNDERLINE},
        {"Universal Access", ICON_FA_UNIVERSAL_ACCESS},
        {"Unlock", ICON_FA_UNLOCK},
        {"Unlock Keyhole", ICON_FA_UNLOCK_KEYHOLE},
        {"Up Down", ICON_FA_UP_DOWN},
        {"Up Down Left Right", ICON_FA_UP_DOWN_LEFT_RIGHT},
        {"Up Long", ICON_FA_UP_LONG},
        {"Up Right And Down Left From Center", ICON_FA_UP_RIGHT_AND_DOWN_LEFT_FROM_CENTER},
        {"Up Right From Square", ICON_FA_UP_RIGHT_FROM_SQUARE},
        {"Upload", ICON_FA_UPLOAD},
        {"User", ICON_FA_USER},
        {"User Astronaut", ICON_FA_USER_ASTRONAUT},
        {"User Check", ICON_FA_USER_CHECK},
        {"User Clock", ICON_FA_USER_CLOCK},
        {"User Doctor", ICON_FA_USER_DOCTOR},
        {"User Gear", ICON_FA_USER_GEAR},
        {"User Graduate", ICON_FA_USER_GRADUATE},
        {"User Group", ICON_FA_USER_GROUP},
        {"User Injured", ICON_FA_USER_INJURED},
        {"User Large", ICON_FA_USER_LARGE},
        {"User Large Slash", ICON_FA_USER_LARGE_SLASH},
        {"User Lock", ICON_FA_USER_LOCK},
        {"User Minus", ICON_FA_USER_MINUS},
        {"User Ninja", ICON_FA_USER_NINJA},
        {"User Nurse", ICON_FA_USER_NURSE},
        {"User Pen", ICON_FA_USER_PEN},
        {"User Plus", ICON_FA_USER_PLUS},
        {"User Secret", ICON_FA_USER_SECRET},
        {"User Shield", ICON_FA_USER_SHIELD},
        {"User Slash", ICON_FA_USER_SLASH},
        {"User Tag", ICON_FA_USER_TAG},
        {"User Tie", ICON_FA_USER_TIE},
        {"User Xmark", ICON_FA_USER_XMARK},
        {"Users", ICON_FA_USERS},
        {"Users Between Lines", ICON_FA_USERS_BETWEEN_LINES},
        {"Users Gear", ICON_FA_USERS_GEAR},
        {"Users Line", ICON_FA_USERS_LINE},
        {"Users Rays", ICON_FA_USERS_RAYS},
        {"Users Rectangle", ICON_FA_USERS_RECTANGLE},
        {"Users Slash", ICON_FA_USERS_SLASH},
        {"Users Viewfinder", ICON_FA_USERS_VIEWFINDER},
        {"Utensils", ICON_FA_UTENSILS},
        {"V", ICON_FA_V},
        {"Van Shuttle", ICON_FA_VAN_SHUTTLE},
        {"Vault", ICON_FA_VAULT},
        {"Vector Square", ICON_FA_VECTOR_SQUARE},
        {"Venus", ICON_FA_VENUS},
        {"Venus Double", ICON_FA_VENUS_DOUBLE},
        {"Venus Mars", ICON_FA_VENUS_MARS},
        {"Vest", ICON_FA_VEST},
        {"Vest Patches", ICON_FA_VEST_PATCHES},
        {"Vial", ICON_FA_VIAL},
        {"Vial Circle Check", ICON_FA_VIAL_CIRCLE_CHECK},
        {"Vial Virus", ICON_FA_VIAL_VIRUS},
        {"Vials", ICON_FA_VIALS},
        {"Video", ICON_FA_VIDEO},
        {"Video Slash", ICON_FA_VIDEO_SLASH},
        {"Vihara", ICON_FA_VIHARA},
        {"Virus", ICON_FA_VIRUS},
        {"Virus Covid", ICON_FA_VIRUS_COVID},
        {"Virus Covid Slash", ICON_FA_VIRUS_COVID_SLASH},
        {"Virus Slash", ICON_FA_VIRUS_SLASH},
        {"Viruses", ICON_FA_VIRUSES},
        {"Voicemail", ICON_FA_VOICEMAIL},
        {"Volcano", ICON_FA_VOLCANO},
        {"Volleyball", ICON_FA_VOLLEYBALL},
        {"Volume High", ICON_FA_VOLUME_HIGH},
        {"Volume Low", ICON_FA_VOLUME_LOW},
        {"Volume Off", ICON_FA_VOLUME_OFF},
        {"Volume Xmark", ICON_FA_VOLUME_XMARK},
        {"Vr Cardboard", ICON_FA_VR_CARDBOARD},
        {"W", ICON_FA_W},
        {"Walkie Talkie", ICON_FA_WALKIE_TALKIE},
        {"Wallet", ICON_FA_WALLET},
        {"Wand Magic", ICON_FA_WAND_MAGIC},
        {"Wand Magic Sparkles", ICON_FA_WAND_MAGIC_SPARKLES},
        {"Wand Sparkles", ICON_FA_WAND_SPARKLES},
        {"Warehouse", ICON_FA_WAREHOUSE},
        {"Water", ICON_FA_WATER},
        {"Water Ladder", ICON_FA_WATER_LADDER},
        {"Wave Square", ICON_FA_WAVE_SQUARE},
        {"Web Awesome", ICON_FA_WEB_AWESOME},
        {"Weight Hanging", ICON_FA_WEIGHT_HANGING},
        {"Weight Scale", ICON_FA_WEIGHT_SCALE},
        {"Wheat Awn", ICON_FA_WHEAT_AWN},
        {"Wheat Awn Circle Exclamation", ICON_FA_WHEAT_AWN_CIRCLE_EXCLAMATION},
        {"Wheelchair", ICON_FA_WHEELCHAIR},
        {"Wheelchair Move", ICON_FA_WHEELCHAIR_MOVE},
        {"Whiskey Glass", ICON_FA_WHISKEY_GLASS},
        {"Wifi", ICON_FA_WIFI},
        {"Wind", ICON_FA_WIND},
        {"Window Maximize", ICON_FA_WINDOW_MAXIMIZE},
        {"Window Minimize", ICON_FA_WINDOW_MINIMIZE},
        {"Window Restore", ICON_FA_WINDOW_RESTORE},
        {"Wine Bottle", ICON_FA_WINE_BOTTLE},
        {"Wine Glass", ICON_FA_WINE_GLASS},
        {"Wine Glass Empty", ICON_FA_WINE_GLASS_EMPTY},
        {"Won Sign", ICON_FA_WON_SIGN},
        {"Worm", ICON_FA_WORM},
        {"Wrench", ICON_FA_WRENCH},
        {"X", ICON_FA_X},
        {"X Ray", ICON_FA_X_RAY},
        {"Xmark", ICON_FA_XMARK},
        {"Xmarks Lines", ICON_FA_XMARKS_LINES},
        {"Y", ICON_FA_Y},
        {"Yen Sign", ICON_FA_YEN_SIGN},
        {"Yin Yang", ICON_FA_YIN_YANG},
        {"Z", ICON_FA_Z},
    };

    inline constexpr size_t kCount = sizeof(kEntries) / sizeof(kEntries[0]);
}
